# Generated by Django 4.2.4 on 2023-09-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0002_remove_page_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_title',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
