# Generated by Django 4.2.4 on 2023-09-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0003_page_page_title_alter_page_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_title',
            field=models.CharField(default='Frank Lobe', max_length=30),
        ),
    ]
