# Generated by Django 4.2.4 on 2023-09-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0004_alter_page_page_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField(default=0)),
                ('paragraph_content', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
