# Generated by Django 4.2.4 on 2023-09-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0005_pageparagraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageparagraph',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
