# Generated by Django 4.2.4 on 2023-09-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0006_pageparagraph_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField(default=0)),
                ('display_order', models.IntegerField(default=0)),
                ('skill_content', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
