# Generated by Django 4.2.4 on 2023-09-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0007_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField(default=0)),
                ('display_order', models.IntegerField(default=0)),
                ('logo', models.CharField(default='', max_length=30)),
                ('program', models.CharField(default='', max_length=30)),
                ('url', models.CharField(default='', max_length=50)),
                ('year', models.IntegerField(default=0)),
            ],
        ),
    ]
