# Generated by Django 4.2.4 on 2023-09-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0008_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField(default=0)),
                ('display_order', models.IntegerField(default=0)),
                ('certification_description', models.CharField(default='', max_length=100)),
                ('certification_institution', models.CharField(default='', max_length=30)),
                ('url', models.CharField(default='', max_length=50)),
                ('year', models.IntegerField(default=0)),
            ],
        ),
    ]
