# Generated by Django 4.2.4 on 2023-09-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0009_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certification_institution',
            field=models.CharField(default='', max_length=50),
        ),
    ]
