# Generated by Django 4.2.4 on 2023-09-04 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0010_alter_certification_certification_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageparagraph',
            name='page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_resume.page'),
        ),
    ]
