# Generated by Django 4.2.4 on 2023-09-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0011_alter_pageparagraph_page_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField(default=0)),
                ('date_range', models.CharField(default='', max_length=30)),
                ('logo', models.CharField(default='', max_length=30)),
                ('title', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=50)),
                ('telephone', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='certification',
            name='page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_resume.page'),
        ),
        migrations.AlterField(
            model_name='education',
            name='page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_resume.page'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_resume.page'),
        ),
        migrations.CreateModel(
            name='EmploymentPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
                ('point_content', models.CharField(default='', max_length=1000)),
                ('employment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_resume.employment')),
            ],
        ),
    ]
