# Generated by Django 4.2.4 on 2023-09-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0012_employment_alter_certification_page_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
