# Generated by Django 4.2.4 on 2023-09-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0013_employment_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='employment',
            name='url',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
