# Generated by Django 4.2.4 on 2023-09-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0014_alter_employment_telephone_alter_employment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='attachment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
