# Generated by Django 4.2.4 on 2023-09-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0015_employment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='attachment_description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
