# Generated by Django 4.2.4 on 2023-09-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0016_employment_attachment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
