# Generated by Django 4.2.4 on 2023-09-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0017_employment_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('online_profile', models.CharField(blank=True, default='', max_length=50)),
                ('email_address', models.CharField(blank=True, default='', max_length=50)),
                ('telephone_number', models.CharField(blank=True, default='', max_length=50)),
                ('company_name', models.CharField(blank=True, default='', max_length=50)),
                ('company_website', models.CharField(blank=True, default='', max_length=50)),
                ('company_address', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('province', models.CharField(blank=True, default='', max_length=50)),
                ('postal_code', models.CharField(blank=True, default='', max_length=50)),
                ('country', models.CharField(blank=True, default='', max_length=50)),
                ('job_posting', models.CharField(blank=True, default='', max_length=50)),
                ('job_type', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
