# Generated by Django 4.2.4 on 2023-09-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0018_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='position_title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
