# Generated by Django 4.2.4 on 2023-09-07 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0020_jobdescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobDescription',
        ),
    ]
