# Generated by Django 4.2.4 on 2023-09-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0021_delete_jobdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='job_description',
            field=models.FileField(blank=True, upload_to='job_descriptions/'),
        ),
    ]
