# Generated by Django 4.2.4 on 2023-09-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0022_contact_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='job_description',
        ),
    ]
