# Generated by Django 4.2.4 on 2023-09-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0023_remove_contact_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='job_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='certification',
            name='url',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='education',
            name='program',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='education',
            name='url',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employment',
            name='date_range',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='employment',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='employment',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentpoint',
            name='point_content',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_name',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='pageparagraph',
            name='paragraph_content',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_content',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
