# Generated by Django 4.2.4 on 2023-09-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0024_skill_job_type_alter_certification_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='job_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
