# Generated by Django 4.2.4 on 2023-09-07 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0025_alter_skill_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
                ('experience_description', models.CharField(default='', max_length=100)),
                ('url', models.CharField(blank=True, default='', max_length=50)),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_resume.page')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
                ('paragraph_content', models.CharField(blank=True, default='', max_length=1000)),
                ('experience_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_resume.experience')),
            ],
        ),
    ]
