# Generated by Django 4.2.4 on 2023-09-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0026_experience_experienceparagraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employment',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
